### ISSUE TITLE
[Bazel CI] Errors loading package: 'android_library' and 'android_binary' are not defined


### ISSUE THREAD

**Issue by sgowroji** [bazel-contrib/rules_jvm_external#1262] opened 2024-10-04 08:42 UTC
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4170#019255c7-940b-46c8-a7a2-be39f08a181f

 Platform: Ubuntu

 Logs: 
```
ERROR: [0m/var/lib/buildkite-agent/builds/bk-docker-qpvh/bazel-org-repo-root/rules_jvm_external/examples/simple/BUILD:1:1: name 'android_library' is not defined
ERROR: [0m/var/lib/buildkite-agent/builds/bk-docker-qpvh/bazel-org-repo-root/rules_jvm_external/examples/simple/BUILD:12:1: name 'android_binary' is not defined
ERROR: [0mpackage contains errors: 
ERROR: [0mpackage contains errors: : name 'android_library' is not defined
ERROR: [0mSkipping '//...': Error evaluating '//...': error loading package '': Package '' contains errors

``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_jvm_external
git reset 2deeda518cf1ccb847c6e188bb3bf7d3f6fb7496  --hard
export USE_BAZEL_VERSION=166eaa09f9cd31836df898ea236e1e0633a73b12
bazel build //... 
 ``` 
 CC Greenteam @mai93

**Comment by jin** [comment] 2024-11-25 04:45
Closing as duplicate of https://github.com/bazel-contrib/rules_jvm_external/pull/1215

**Closed by jin** 2024-11-25 04:45 UTC
